Repository jhyep/db-team4-project, pull requests merged in 2023-12, with the labels that each got.

#16 [BE/FE] 한줄평 및 독후감 불러오기 및 수정 구현
  client/src/components/Button/index.jsx
  client/src/pages/BookInfo/BookDescription/index.jsx
  client/src/pages/BookInfo/Ratings/index.jsx
  client/src/pages/BookInfo/Reviews/index.jsx
  client/src/pages/BookInfo/index.jsx
  server/routes/book.js
  server/routes/bookUtil/infoBook.js
  server/routes/dbUtil/dbBookUtils/dbBookUtils.js
  server/routes/dbUtil/dbUtils.js
Labels: 💻 FE, ⚙️ BE, ✨ Feature

#17 [FE] 한줄평 독후감 입력란 요구사항 메시지 표시 수정
  client/src/pages/BookInfo/Ratings/index.jsx
  client/src/pages/BookInfo/Reviews/index.jsx
Labels: 💻 FE, ♻️ Refactor

#19 [BE] 동시성 제어 구현(트랜잭션)
  server/routes/bookUtil/infoBook.js
  server/routes/dbUtil/dbBookUtils/dbBookUtils.js
  server/routes/dbUtil/dbUserUtils/dbUserUtils.js
  server/routes/userUtil/signup.js
Labels: ⚙️ BE, ✨ Feature
